receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

  debug:
    verbosity: detailed

processors:
  batch:
  
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["service_name"], resource.attributes["service.name"])
          - set(attributes["loki.attribute.labels"], "service_name")

  resource:
    attributes:
      - key: loki.resource.labels
        value: service.name
        action: insert

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [resource, transform, batch]
      exporters: [loki, debug]
