#!/bin/bash

echo "Starting traffic generator..."
echo "Press Ctrl+C to stop"

while true; do
  # Generate a valid user
  USER_ID=$RANDOM
  curl -s -X POST http://localhost:3001/users -H "Content-Type: application/json" -d "{\"name\":\"User $USER_ID\", \"email\":\"user$USER_ID@test.com\"}" > /dev/null
  
  # Fetch the valid user (might fail if sequence matches generated DB ID, but generally works if we use the returned ID, however for simplicity we just guess or use $USER_ID which causes 404s, but that's fine for traffic)
  # Actually, the ID generated by Postgres is sequential. $USER_ID is just a random string we put in name.
  # Let's just hardcode ID 1 for GET to succeed, assuming ID 1 exists.
  curl -s "http://localhost:3001/users/1" > /dev/null
  
  # Generate a 404 on user-service
  curl -s "http://localhost:3001/users/99999" > /dev/null
  
  # Generate a 5xx error on user-service (violates NOT NULL email constraint)
  curl -s -X POST http://localhost:3001/users -H "Content-Type: application/json" -d "{\"name\":\"Invalid User\"}" > /dev/null

  # Generate a valid order
  curl -s -X POST http://localhost:3002/orders -H "Content-Type: application/json" -d "{\"user_id\": 1, \"product\": \"Laptop\", \"amount\": 1200}" > /dev/null

  # Generate a 404 on order-service
  curl -s "http://localhost:3002/orders/99999" > /dev/null

  # Generate a 5xx error on order-service (violates NOT NULL amount constraint)
  curl -s -X POST http://localhost:3002/orders -H "Content-Type: application/json" -d "{\"user_id\": 1, \"product\": \"Invalid Order\"}" > /dev/null

  # Trigger notification service health endpoint
  curl -s "http://localhost:3003/health" > /dev/null

  echo "Generated a batch of requests (200s, 404s, 500s)..."
  sleep 1
done
