{
 "title": "Node.js Microservices",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "HTTP Requests Rate (by Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count[5m])) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "HTTP Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_sum[5m])) by (exported_job) / sum(rate(http_server_duration_milliseconds_count[5m])) by (exported_job)",
     "legendFormat": "{{exported_job}} avg latency"
    }
   ]
  },
  {
   "title": "HTTP Request Failures (5xx & 4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_status_code=~\"5..\"}[5m])) by (exported_job)",
     "legendFormat": "{{exported_job}} 5xx"
    },
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_status_code=~\"4..\"}[5m])) by (exported_job)",
     "legendFormat": "{{exported_job}} 4xx"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(exported_job) (rate(system_cpu_time_seconds_total{state!=\"idle\"}[5m])) / sum by(exported_job) (rate(system_cpu_time_seconds_total[5m])) * 100",
     "legendFormat": "{{exported_job}} %"
    }
   ]
  },
  {
   "title": "Orders Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(order_created_total)", "legendFormat": "Total Orders" }
   ]
  }
 ]
}